In [4]:
import pandas as pd
import numpy as np

In [7]:
data=pd.read_csv("deliveries.csv")

In [20]:
data.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [29]:
data.drop_duplicates('total_runs').sort_values(by='total_runs')

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,TS Mills,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
17,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,4,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
251,2,1,Mumbai Indians,Rising Pune Supergiant,1,4,JC Buttler,PA Patel,AB Dinda,0,...,0,0,0,0,5,0,5,NaN,NaN,NaN
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
2443,11,1,Kings XI Punjab,Kolkata Knight Riders,14,5,DA Miller,WP Saha,C de Grandhomme,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN

In [32]:
batsman_groupby=data.groupby('batsman')

In [33]:
batsman_groupby

In [41]:
batsman_groupby.get_group('MS Dhoni').sort_values(by='batsman_runs',ascending=False)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
68290,289,1,Chennai Super Kings,Delhi Daredevils,12,1,MS Dhoni,S Badrinath,AB McDonald,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
10065,43,1,Rising Pune Supergiant,Sunrisers Hyderabad,19,5,MS Dhoni,MK Tiwary,B Kumar,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
148764,629,2,Rising Pune Supergiants,Kings XI Punjab,20,7,MS Dhoni,R Ashwin,AR Patel,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
132481,559,1,Chennai Super Kings,Mumbai Indians,19,1,MS Dhoni,P Negi,R Vinay Kumar,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
148729,629,2,Rising Pune Supergiants,Kings XI Punjab,15,5,MS Dhoni,NLTC Perera,AR Patel,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99019,418,1,Chennai Super Kings,Kolkata Knight Riders,16,6,MS Dhoni,SK Raina,SP Narine,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
98202,414,2,Chennai Super Kings,Sunrisers Hyderabad,20,2,MS Dhoni,CH Morris,A Ashish Reddy,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
98201,414,2,Chennai Super Kings,Sunrisers Hyderabad,20,1,MS Dhoni,CH Morris,A Ashish Reddy,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
486,2,2,Rising Pune Supergiant,Mumbai Indians,19,3,MS Dhoni,SPD Smith,JJ Bumrah,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
148761,629,2,Rising Pune Supergiants,Kings XI Punjab,20,4,MS Dhoni,R Ashwin,AR Patel,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [49]:
batsman_groupby['batsman_runs'].sum().sort_values(ascending=False).head()

batsman
SK Raina     4548
V Kohli      4423
RG Sharma    4207
G Gambhir    4132
DA Warner    4014
Name: batsman_runs, dtype: int64

In [85]:
mask=data['batsman_runs']==6
chaka=data[mask]

In [72]:
chaka

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
47,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,4,MC Henriques,S Dhawan,TM Head,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
75,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,13,2,Yuvraj Singh,MC Henriques,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
89,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,3,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
91,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,5,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150395,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,10,2,V Kohli,CH Gayle,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150413,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,2,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150428,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,15,5,SR Watson,KL Rahul,MC Henriques,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150440,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,5,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150453,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,6,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

In [93]:
chaka.groupby('batsman')['batsman_runs'].size().sort_values(ascending=False).head(10)

batsman
CH Gayle          266
SK Raina          174
RG Sharma         173
DA Warner         160
V Kohli           160
AB de Villiers    158
MS Dhoni          156
YK Pathan         149
KA Pollard        148
Yuvraj Singh      141
Name: batsman_runs, dtype: int64

In [102]:
chaka.shape

(6523, 21)

In [112]:
vk=data[data['batsman']=='V Kohli']

In [113]:
vk.groupby('bowling_team')['batsman_runs'].sum().sort_values(ascending=False).head(10)

bowling_team
Chennai Super Kings        706
Delhi Daredevils           661
Kings XI Punjab            483
Mumbai Indians             447
Sunrisers Hyderabad        439
Kolkata Knight Riders      391
Deccan Chargers            306
Gujarat Lions              283
Rajasthan Royals           258
Rising Pune Supergiants    188
Name: batsman_runs, dtype: int64

In [119]:
def run_scored(batsman_name):
    vk=data[data['batsman']==batsman_name]
    return vk.groupby('bowling_team')['batsman_runs'].sum().sort_values(ascending=False).head(10)
    #this will give how much a batsman score against a team (batsman top 10 best scores)

In [120]:
run_scored('S Dhawan')

bowling_team
Mumbai Indians                 536
Kings XI Punjab                530
Kolkata Knight Riders          452
Chennai Super Kings            448
Royal Challengers Bangalore    399
Delhi Daredevils               397
Rajasthan Royals               331
Gujarat Lions                  127
Deccan Chargers                118
Rising Pune Supergiants         89
Name: batsman_runs, dtype: int64

In [129]:
overs=data[data['over']>15]

In [134]:
x=overs.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False)
y=x>200
x[y]

batsman
MS Dhoni            1224
KA Pollard           838
RG Sharma            748
YK Pathan            584
RA Jadeja            576
AB de Villiers       570
V Kohli              546
JP Duminy            518
Yuvraj Singh         516
IK Pathan            465
KD Karthik           463
SK Raina             458
AT Rayudu            425
JA Morkel            425
MK Tiwary            423
Harbhajan Singh      418
DJ Bravo             409
BJ Hodge             385
DA Miller            360
KM Jadhav            338
SPD Smith            316
PP Chawla            311
NV Ojha              304
SS Tiwary            300
WP Saha              295
JP Faulkner          294
AD Mathews           289
S Badrinath          283
RV Uthappa           275
AM Rahane            268
P Kumar              268
Y Venugopal Rao      260
DPMD Jayawardene     246
S Dhawan             243
R Vinay Kumar        235
DJ Hussey            234
JH Kallis            231
AR Patel             229
DA Warner            228
A Mishra             225
MK Pandey            224
STR Binny            218
LRPL Taylor          204
Name: batsman_runs, dtype: int64

In [135]:
data2=pd.read_csv('matches.csv')

In [143]:
new_data=data.merge(data2, left_on='match_id',right_on='id')

In [163]:
new_data.groupby(['season','batsman'])['batsman_runs'].sum().reset_index().sort_values(by='batsman_runs',ascending=False).drop_duplicates(subset='season',keep='first' ).sort_values(by='season')

      season       batsman  batsman_runs
115     2008      SE Marsh           616
229     2009     ML Hayden           572
446     2010  SR Tendulkar           618
502     2011      CH Gayle           608
684     2012      CH Gayle           733
910     2013    MEK Hussey           733
1088    2014    RV Uthappa           660
1148    2015     DA Warner           562
1383    2016       V Kohli           973
1422    2017     DA Warner           641